### ISSUE TITLE
Blog post comment

### ISSUE THREAD

**Issue by Derek-Jones** [softwarebyscience/function-length#1]
Sorry for commenting here.  Submitting a comment via your blog gets the response: "Blocked as suspected bot."

I'm pleased to see someone else taking an active interest in an evidence-based approach to software engineering.  I had not seen the "Old habits die hard" paper before.

You can find a discussion of my own work here: http://shape-of-code.coding-guidelines.com/2020/06/30/beta-evidence-based-software-engineering-book/

A couple of points:

o It can be very misleading to plot defect density against LOC (the issue is the same variable appearing on the x and y-axis).  For an analysis of the issues see: https://www.researchgate.net/publication/309206581_The_Optimal_Class_Size_for_Object-Oriented_Software_A_Replicated_Study

o In Java most methods are short, and 60% of Java code appears in methods containing five of less lines.  See figure 7.22 in http://knosof.co.uk/ESEUR/ESEUR-draft.pdf

**Comment by softwarebyscience** [comment]
Hi Derek, your upcoming book looks really interesting. It's also great you got something new out of my post, even though you're obviously very experienced in this field.

I won't have time to take a look at the paper you linked until end of this week, but I'll make sure to fully understand it. Is there an email (or something else) I could use to contact you for discussion?

I'll also have to figure out what's wrong with the commenting functionality...

**Comment by Derek-Jones** [comment]
derek@knosof.co.uk

**Comment by softwarebyscience** [comment]
Thanks. Deleting this issue.
